#!/usr/bin/env bash
# setup-azure-ddns.sh — wire Metis up to Azure DNS for both the azure-ddns
# package and certbot's dns-azure plugin. Run once after first browser login
# (so `az login` can pop a browser auth window).
#
# Idempotent: safe to re-run any number of times. Each run:
#   - reuses the existing 'metis-ddns' app reg if found (else creates one;
#     the SP display name is kept as 'metis-ddns' for historical continuity
#     — renaming it would orphan the existing role assignment)
#   - ensures the SP exists (no-op if already there)
#   - rotates the secret (replaces, doesn't append — old one invalidated)
#   - ensures the role assignment exists (DNS Zone Contributor on the zone)
#   - rewrites /etc/azure-ddns.env and /etc/letsencrypt/azure.ini with the
#     fresh creds
#   - restarts azure-ddns
#
# Tested 2026-04-23 against Azure CLI 2.85.0. The all-in-one
# `az ad sp create-for-rbac` is currently broken under Python 3.14
# (argparse %Y bug) — this script uses the piecemeal `ad app` /
# `ad sp` / `role assignment` commands which are unaffected.

set -euo pipefail

# ---- Locked config from project memory (project_azure_ddns.md) ----
TENANT_ID="bb462d15-cc1e-4a17-b0db-3ba7fcd00b21"   # Butler Software LLC
SUBSCRIPTION_ID="ab78414a-6bf4-4d87-b27c-954c41aa8081"
RESOURCE_GROUP="rhombus"
DNS_ZONE="rhombus.rocks"
RECORD_NAME="metis"
SP_DISPLAY_NAME="metis-ddns"

ZONE_SCOPE="/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}/providers/Microsoft.Network/dnszones/${DNS_ZONE}"

# ---- Helpers ----
log()  { printf '[+] %s\n' "$*"; }
warn() { printf '[!] %s\n' "$*" >&2; }
die()  { printf '[✗] %s\n' "$*" >&2; exit 1; }

# ---- Pre-flight ----
command -v az >/dev/null || die "azure-cli not installed (sudo pacman -S azure-cli)"
command -v jq >/dev/null || die "jq not installed (sudo pacman -S jq)"

# Verify auth — prompt to login if not yet authenticated, AND make sure
# the active context is on the right tenant. Without --tenant, az login
# defaults to the user's HOME tenant, which doesn't have the rhombus.rocks
# subscription on this account — script then fails with:
#   ERROR: No subscriptions found for <user>.
# Forcing --tenant skips the multi-tenant fan-out and lands on Butler
# Software LLC (where the DNS zone lives) up-front.
#
# `--use-device-code-if-no-browser` was hallucinated — it doesn't exist
# in any az version. Plain `az login` auto-detects browser availability;
# `--use-device-code` forces device-code unconditionally if needed.
current_tenant=$(az account show --query tenantId -o tsv 2>/dev/null || true)
if [[ "$current_tenant" != "$TENANT_ID" ]]; then
    log "azure-cli not authenticated to tenant $TENANT_ID; running 'az login --tenant $TENANT_ID'..."
    az login --tenant "$TENANT_ID" >/dev/null
fi

current_sub=$(az account show --query id -o tsv)
if [[ "$current_sub" != "$SUBSCRIPTION_ID" ]]; then
    log "Switching active subscription to $SUBSCRIPTION_ID..."
    az account set --subscription "$SUBSCRIPTION_ID"
fi

log "Tenant: $TENANT_ID"

# Verify zone exists (cheap read; fail loudly if missing rather than create
# the SP and discover later that the role assignment scope is wrong).
if ! az network dns zone show -g "$RESOURCE_GROUP" -n "$DNS_ZONE" >/dev/null 2>&1; then
    die "DNS zone '$DNS_ZONE' not found in resource group '$RESOURCE_GROUP'"
fi

# ---- 1. App registration (idempotent: check before create) ----
APP_ID=$(az ad app list --display-name "$SP_DISPLAY_NAME" --query '[0].appId' -o tsv 2>/dev/null || true)
if [[ -z "$APP_ID" ]]; then
    log "Creating app registration '$SP_DISPLAY_NAME'..."
    APP_ID=$(az ad app create --display-name "$SP_DISPLAY_NAME" --query appId -o tsv)
else
    log "Reusing existing app '$SP_DISPLAY_NAME' (appId=$APP_ID)"
fi

# ---- 2. Service principal (idempotent: just runs cleanly if already there) ----
log "Ensuring service principal exists for app..."
az ad sp create --id "$APP_ID" >/dev/null 2>&1 || true   # already-exists returns 0 in current az

# ---- 3. Rotate credential (REPLACE behavior — old secret invalidated) ----
log "Rotating secret (default 1y; --years 2 blocked by az+py3.14 bug, will re-add when fixed)..."
cred_json=$(az ad app credential reset \
    --id "$APP_ID" \
    --display-name "${SP_DISPLAY_NAME}-secret" \
    -o json)
CLIENT_SECRET=$(echo "$cred_json" | jq -r .password)
[[ -n "$CLIENT_SECRET" && "$CLIENT_SECRET" != "null" ]] || die "credential reset returned no password"

# ---- 4. Role assignment (DNS Zone Contributor on the zone) ----
log "Ensuring DNS Zone Contributor assignment on $DNS_ZONE..."
az role assignment create \
    --assignee "$APP_ID" \
    --role "DNS Zone Contributor" \
    --scope "$ZONE_SCOPE" \
    >/dev/null 2>&1 || log "  (role assignment already exists — fine)"

# ---- 5. Write /etc/azure-ddns.env (mode 600, root-owned) ----
log "Writing /etc/azure-ddns.env..."
sudo install -d -m 755 /etc
sudo tee /etc/azure-ddns.env >/dev/null <<EOF
# Generated by setup-azure-ddns.sh on $(date -Iseconds)
# Re-run that script to rotate the secret (old one is invalidated automatically).
AZ_TENANT_ID=${TENANT_ID}
AZ_CLIENT_ID=${APP_ID}
AZ_CLIENT_SECRET=${CLIENT_SECRET}
AZ_SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
AZ_RESOURCE_GROUP=${RESOURCE_GROUP}
AZ_DNS_ZONE=${DNS_ZONE}
AZ_DNS_RECORD=${RECORD_NAME}
AZ_DNS_TTL=300

# Stack toggles. Metis is on an IPv6-only DDNS path (the home router does
# CG-NAT v4, so a public-IP A record would point at the carrier gateway).
DDNS_DISABLE_IPV4=1
DDNS_DISABLE_IPV6=0

# Pin to the kernel-managed stable SLAAC GUA. Without this, source-selection
# defaults to the temporary RFC 4941 address, which rotates every ~24h —
# DNS would churn and clients would chase a moving target. See
# https://github.com/fnrhombus/azure-ddns README "IPv6 source selection".
AZURE_DDNS_IPV6_SELECT=slaac-stable
EOF
sudo chmod 600 /etc/azure-ddns.env
sudo chown root:root /etc/azure-ddns.env

# ---- 6. Write /etc/letsencrypt/azure.ini for certbot dns-azure plugin ----
log "Writing /etc/letsencrypt/azure.ini..."
sudo install -d -m 755 /etc/letsencrypt
sudo tee /etc/letsencrypt/azure.ini >/dev/null <<EOF
# Generated by setup-azure-ddns.sh on $(date -Iseconds)
dns_azure_sp_client_id     = ${APP_ID}
dns_azure_sp_client_secret = ${CLIENT_SECRET}
dns_azure_tenant_id        = ${TENANT_ID}
dns_azure_environment      = AzurePublicCloud
dns_azure_zone1            = ${DNS_ZONE}:/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP}
EOF
sudo chmod 600 /etc/letsencrypt/azure.ini
sudo chown root:root /etc/letsencrypt/azure.ini

# ---- 7. Kick the DDNS service ----
log "Starting azure-ddns service..."
sudo systemctl restart azure-ddns.service || warn "azure-ddns.service restart failed; check 'systemctl status azure-ddns'"
sudo systemctl enable azure-ddns.timer >/dev/null 2>&1 || true

# ---- 8. Report ----
echo
log "Azure DDNS wired. Summary:"
echo "  Tenant:      $TENANT_ID"
echo "  App / SP:    $APP_ID  ($SP_DISPLAY_NAME)"
echo "  Scope:       $DNS_ZONE  in resource group $RESOURCE_GROUP"
echo "  Records:     ${RECORD_NAME}.${DNS_ZONE} A + AAAA (next ddns run will populate)"
echo "  Secret life: 1 year (rotate by re-running this script)"
echo
echo "Next step: issue Let's Encrypt cert"
echo "  sudo certbot certonly --authenticator dns-azure \\"
echo "      --dns-azure-credentials /etc/letsencrypt/azure.ini \\"
echo "      --dns-azure-propagation-seconds 60 \\"
echo "      -d ${RECORD_NAME}.${DNS_ZONE}"
